### ISSUE TITLE
Downloading the plugin manifest failed

### ISSUE THREAD

**Issue by KaeganJ** [Arnuh/RuneLiteHijack#3]
After installing, when opening the plugin manager it just shows a message "Downloading the plugin manifest failed".

**Comment by Arnuh** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client will show how to get the logs which will better explain the reason for that error.

Something is obviously wrong with how you're connecting to the "base" plugin manifest. Can see if it's accessible normally https://files.arnah.ca/runelite/plugins.json

You can also build RuneLiteHijack yourself and modify the default plugin hub which only exists for others to download a plugin & hook up custom pluginhubs anyway. I probably need to give a bit more documentation on such things.

**Comment by JoshuaA392** [comment]
Kind of hijacking this post, but I figured since its a similar "issue" really my own lack of knowledge and was hoping you could point me in the right direction. I'm trying to create my own manifest and clearly lack the understanding even after reading most of the code. I've based this off of the example you provided above (https://files.arnah.ca/runelite/plugins.json) and reading the code but I'm afraid I'm still not doing it right. 

`[{
	"internalName": "exampleplugin",
	"hash": "d1f3fe8dc8136b10d7795c6f06865161dc2afc6b5523ca396403907ab5aa3b30",
	"size": 339089,
	"plugins": [
		"net.runelite.client.plugins.pvm.examplePlugin"
	],
	"displayName": "example plugin",
	"description": "some shitty plugin",
	"provider": "test",
	"releases": [{
		"internalName": "exampleplugin",
		"releases": [{
			"url": "inserturlhere",
			"sha512sum": "d1f3fe8dc8136b10d7795c6f06865161dc2afc6b5523ca396403907ab5aa3b30"
		}]
	}]
}]`

Any advice would he helpful, thanks.

**Comment by Arnuh** [comment]
@JoshuaA392 

I'd suggest avoiding the "releases" setup outside of just quick copy-pasting. Either way, that part is setup incorrectly as you have it as a releases list under another releases list. https://hastebin.com/jamozusito.json should work but I haven't personally tested it.

The 'official' way is to not include "releases" and instead have a folder/file structure like

```
plugins.json
provider_name
  internalName.jar
```
Then just point the 2 urls in `RuneLiteHijackProperties` to a webpage hosting those structure.

**Comment by Arnuh** [comment]
https://github.com/Arnuh/RuneLiteHijack/commit/a6f9a63f18dc3b7b3a035731bfb39f7b9ef8370b should remove the error mentioned here?

**Comment by Blunkie** [comment]
Im hijacking this post x2 lol when you changed it from files.arnah to githubusercontent does that mean it can pull plugins from a github repo? If possibly you should make it so you can just drag plugins into the runelitehijack plugins folder

**Comment by Blunkie** [comment]
but i mean i also still don't understand how to pull the plugins through servers like that but this project taught me a lot and changed the community as a whole what you did really was amazing man thank you. Changed a lot and brought the community out of a long nasty pay period for clients we were in the dark ages and this project was the light i dont know how much you look at the plugin community but your work blessed it.

**Comment by Arnuh** [comment]
> If possibly you should make it so you can just drag plugins into the runelitehijack plugins folder

Is possible, I assume most people just want the openosrs setup of the Manifest & extensions.idx to identify the required information

> does that mean it can pull plugins from a github repo?

Yes, the "raw github user content" pages can be used to act as just normal webpages and is a dropin replacement option


Closing this since the OP isn't replying and any future conversations should be in separate issues.
